services:
  web:
    image: registry.digitalocean.com/my-image-register/market-place:7af86c5f539fcf7b7b7ee5284f90e42a9ad34174
    expose:
      - "8080"
    restart: unless-stopped
    environment:
      - CONNECTION_STRING=Host=146.190.229.254;Port=5432;Database=marketdb;Username=postgres;Password=mysecurepassword
    command: >
      sh -c "dotnet ef database update --project ./TechStation.Data --startup-project ../TechStation.Api && dotnet TechStation.Api.dll"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
  haproxy:
    image: haproxy:3.2.0-alpine3.22
    ports:
      - "80:80"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    restart: unless-stopped
    depends_on:
      - web
