services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: unless-stopped

  web:
    image: registry.digitalocean.com/my-image-register/market-place:9af5437cc4d59f617b9f74ca19ac411e53ace39b
    depends_on:
      - nginx
    ports:
      - "5000:8080"
    restart: unless-stopped

