services:
  web:
    image: registry.digitalocean.com/my-image-register/market-place:ce7826d1da190b063ed6d5f9778c280e6909e0a7
    ports:
      - "5000:8080"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]  # yoki kerakli endpoint
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
