services:
  db:
    image: postgres:17-alpine3.21
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: My!Passw0rd
      POSTGRES_DB: marketplacedb
    ports:
      - "5434:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  web:
    image: registry.digitalocean.com/image-register/market-place:b3e7a7d2100cc965dfdf56a2c346df3f4c80546c
    depends_on:
      - db
    ports:
      - "5000:8080"
    environment:
      ConnectionStrings__DefaultConnection: "Host=db;Port=5432;Database=marketplacedb;Username=postgres;Password=My!Passw0rd;Trust Server Certificate=true;"
    restart: unless-stopped

volumes:
  db-data:
