services:
  web:
    image: registry.digitalocean.com/my-image-register/market-place:7af86c5f539fcf7b7b7ee5284f90e42a9ad34174
    expose:
      - "8080"
    restart: unless-stopped
    environment:
      - CONNECTION_STRING=Host=postgres;Port=5432;Database=marketdb;Username=postgres;Password=mysecurepassword
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    depends_on:
      - postgres

  postgres:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: marketdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecurepassword
    volumes:
      - postgres_data:/var/lib/postgresql/data

  prometheus:
    image: prom/prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
